import pandas as pd
import numpy as np
import io

# ==========================================
# PHẦN 1: GIẢ LẬP DỮ LIỆU (MOCK DATA)
# Sếp dùng phần này để test logic nếu chưa có file thật
# ==========================================
csv_data_content = """
Report Date: 2023-10-01 to 2023-10-27
Generated by: IronSource Network

Date,Country,Installs,LTV D0,LTV D1,LTV D3,LTV D7,LTV D14,LTV D30
2023-10-27,US,1500,0.05,0.12,0.25,0.40,0.55,0.80
2023-10-27,VN,3000,0.01,0.02,0.04,0.06,0.08,0.10
2023-10-27,BR,2000,0.02,0.04,0.07,0.11,0.15,0.20
2023-10-26,US,1450,0.06,0.13,0.26,0.41,0.56,0.82
2023-10-26,Brazil,100,0.00,0.00,0.00,0.00,0.00,0.00
"""
# Lưu ý dòng cuối: 'Brazil' nằm ở cột Country là đúng, 
# nhưng nếu file lỗi, chữ 'Brazil' có thể bị nhảy sang cột LTV gây ra lỗi sếp gặp.

# ==========================================
# PHẦN 2: CORE LOGIC XỬ LÝ DỮ LIỆU (QUAN TRỌNG)
# ==========================================

def clean_currency(x):
    """
    Hàm phụ trợ: Làm sạch các ký tự tiền tệ nếu có (ví dụ: $0.05 -> 0.05)
    """
    if isinstance(x, str):
        return x.replace('$', '').replace(',', '').strip()
    return x

def process_monetization_report(file_input):
    """
    Hàm xử lý chính: Đọc file, tìm header chuẩn, ép kiểu an toàn.
    Input: Đường dẫn file hoặc buffer.
    Output: DataFrame sạch đẹp.
    """
    print("--- Bắt đầu xử lý file ---")
    
    try:
        # BƯỚC 1: Đọc file thô để tìm dòng Header thực sự
        # Nhiều report (như của IronSource, AppLovin) có vài dòng meta data ở đầu.
        # Ta sẽ đọc thử 10 dòng đầu để tìm dòng chứa chữ "Date" hoặc "Country".
        
        header_row_index = 0
        if isinstance(file_input, str):
            # Nếu là đường dẫn file
            df_temp = pd.read_csv(file_input, header=None, nrows=10)
        else:
            # Nếu là string buffer (như ví dụ này)
            file_input.seek(0)
            df_temp = pd.read_csv(file_input, header=None, nrows=10)
            file_input.seek(0) # Reset con trỏ về đầu

        # Tìm dòng chứa cột 'Country' hoặc 'Installs'
        found = False
        for idx, row in df_temp.iterrows():
            row_str = row.astype(str).str.lower().tolist()
            if 'country' in row_str or 'installs' in row_str:
                header_row_index = idx
                found = True
                print(f"-> Đã tìm thấy Header chuẩn ở dòng: {idx}")
                break
        
        if not found:
            print("Warning: Không tìm thấy header chuẩn, mặc định dùng dòng 0.")

        # BƯỚC 2: Đọc lại file với header đúng
        if isinstance(file_input, str):
            df = pd.read_csv(file_input, header=header_row_index)
        else:
            df = pd.read_csv(file_input, header=header_row_index)

        # Chuẩn hóa tên cột (xóa khoảng trắng, viết thường)
        df.columns = df.columns.str.strip()
        print(f"-> Các cột tìm thấy: {df.columns.tolist()}")

        # BƯỚC 3: Xử lý ép kiểu dữ liệu (Fix lỗi 'Brazil' string to float)
        
        # 3.1. Cột Date: Chuyển về datetime
        if 'Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
            # Xóa các dòng mà Date bị NaT (do dòng tổng cộng hoặc dòng rác cuối file)
            df = df.dropna(subset=['Date'])
        
        # 3.2. Cột Country: Ép về String chuẩn
        if 'Country' in df.columns:
            df['Country'] = df['Country'].astype(str).str.strip()

        # 3.3. Các cột Metrics (Số liệu): Installs, LTV, Revenue...
        # Tự động nhận diện các cột cần là số
        numeric_cols = [c for c in df.columns if c not in ['Date', 'Country', 'Campaign', 'Ad Network']]
        
        print(f"-> Đang ép kiểu số cho các cột: {numeric_cols}")

        for col in numeric_cols:
            # Clean ký tự lạ trước ($ ,)
            df[col] = df[col].apply(clean_currency)
            
            # Ép kiểu số mạnh tay (errors='coerce' sẽ biến lỗi thành NaN)
            df[col] = pd.to_numeric(df[col], errors='coerce')
            
            # Điền 0 vào các ô bị NaN (ví dụ ô trống hoặc ô chứa text rác)
            df[col] = df[col].fillna(0)

        # BƯỚC 4: Tính toán thêm chỉ số (Optional - Sếp hay cần cái này)
        # Ví dụ: Tính ARPU D0 (LTV D0) nếu chưa có, hoặc check ROI
        # Ở đây em ví dụ sort lại cho đẹp
        df = df.sort_values(by=['Date', 'Installs'], ascending=[False, False])

        print("--- Xử lý hoàn tất ---")
        return df

    except Exception as e:
        print(f"!!! LỖI NGHIÊM TRỌNG: {str(e)}")
        return None

# ==========================================
# PHẦN 3: CHẠY THỬ (MAIN)
# ==========================================

if __name__ == "__main__":
    # Tạo file giả lập từ string ở trên để test
    dummy_file = io.StringIO(csv_data_content)
    
    # Gọi hàm xử lý
    df_result = process_monetization_report(dummy_file)
    
    if df_result is not None:
        print("\n=== KẾT QUẢ DATAFRAME ===")
        print(df_result)
        
        # Check thử kiểu dữ liệu xem đã chuẩn float chưa
        print("\n=== DATA TYPES ===")
        print(df_result.dtypes)
        
        # Sếp có thể xuất ra Excel mới ở đây
        # df_result.to_excel("report_clean.xlsx", index=False)
        # print("\n-> Đã xuất file report_clean.xlsx")